services:
  - type: web
    name: campus-voice-backend
    env: node
    region: singapore
    branch: main
    rootDir: backend
    buildCommand: npm install --production=false
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: tmsl2026campusvoice@secretkey
      - key: FRONTEND_URL
        value: https://college-complain-management.vercel.app
      - key: DATABASE_URL
        sync: false

databases:
  - name: campus-voice-db
    region: singapore
    plan: free
